### ISSUE TITLE
Why does this escape { and } when HTML::Entities doesn't?

### ISSUE THREAD

**Issue by neilb** [tokuhirom/HTML-Escape#5]
I've switched from using HTML::Entities, and in testing discovered a difference between behaviour.

`HTML::Entities` doesn't escape opening and closing curlies (`{` and `}`), and most recommendations on what you should encode (eg [this page from W3C](https://www.w3.org/International/questions/qa-escapes)) don't suggest it.

Is there a reason why these are being encoded, or could this be dropped?

Cheers,
Neil

**Comment by bes-internal** [comment]
Because this 5e4e7a033d009d761d487e0751b8a83d89e586f7 prevent XSS in (sic!) Angular templates

But this is funny shit, because here is not escape even though recommended owasp:
 ```
& --> &amp;
 < --> &lt;
 > --> &gt;
 " --> &quot;
 ' --> &#x27;     &apos; not recommended because its not in the HTML spec (See: section 24.4.1) &apos; is in the XML and XHTML specs.
/ --> &#x2F;     forward slash is included as it helps end an HTML entity
```

http://security.stackexchange.com/questions/49852/owasp-escaping-recommendation-why
https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet

**Comment by tokuhirom** [comment]
Yep. It's a hack for angular.
